# Generated by Django 4.2.21 on 2025-06-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_promocode_discount_type_stripepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_2',
        ),
    ]
